spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uap
    username: uap
    password: uap

  ldap:
    urls: ldap://localhost:389
    base: dc=maxcrc,dc=com
    username: cn=Manager,${spring.ldap.base}
    password: secret
    user-dn-pattern: cn={0},ou=users,${spring.ldap.base}
    group-search-base: ou=groups,${spring.ldap.base}

  mail:
    host: smtp.neusoft.com
    port: 587
    username: 
    password: 
    protocol: smtp
    
  jpa:
    show-sql: true

logging:
  config: classpath:config/logback.xml

server:
  port: 8001
