datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/uap?serverTimezone=CST
  username: uap
  password: uap

ldap:
  url: ldap://localhost:389
  base: dc=maxcrc,dc=com
  userDn: cn=Manager,dc=maxcrc,dc=com
  password: secret

spring:
  mail:
    host: smtp.neusoft.com
    port: 587
    username:
    password:
    protocol: smtp
    from:

logging:
  config: classpath:config/logback.xml

server:
  port: 8001
